name: lpinyin
description: Chinese character conversion pinyin library.Accurate and complete Chinese character dictionary.Fast conversion.
version: 2.0.2
homepage: https://github.com/flutterchina/lpinyin

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"